# Generated by Django 2.1.2 on 2018-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
        migrations.AddField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='user', verbose_name='프로필 이미지'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce',
            field=models.TextField(blank=True, verbose_name='소개'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.URLField(blank=True, max_length=150, verbose_name='사이트'),
        ),
    ]
